@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Jun 03 11:11:53 -0400 2025
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_dds_to_fft_behav -key {Behavioral:sim_1:Functional:tb_dds_to_fft} -tclbatch tb_dds_to_fft.tcl -protoinst "protoinst_files/bd_5de7.protoinst" -protoinst "protoinst_files/axi_stream_bd.protoinst" -view O:/ENGS128/fft/tb_dds_to_fft_behav.wcfg -log simulate.log"
call xsim  tb_dds_to_fft_behav -key {Behavioral:sim_1:Functional:tb_dds_to_fft} -tclbatch tb_dds_to_fft.tcl -protoinst "protoinst_files/bd_5de7.protoinst" -protoinst "protoinst_files/axi_stream_bd.protoinst" -view O:/ENGS128/fft/tb_dds_to_fft_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
