# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/hw/zybo_z7-10_constraints.xdc

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: ip/fir_bsf_0/fir_bsf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_bsf_0 || ORIG_REF_NAME==fir_bsf_0} -quiet] -quiet

# IP: ip/fir_bpf_0/fir_bpf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_bpf_0 || ORIG_REF_NAME==fir_bpf_0} -quiet] -quiet

# IP: ip/fir_hpf_0/fir_hpf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_hpf_0 || ORIG_REF_NAME==fir_hpf_0} -quiet] -quiet

# IP: ip/fir_lpf_0_1/fir_lpf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_lpf_0 || ORIG_REF_NAME==fir_lpf_0} -quiet] -quiet

# Block Designs: bd/axi_stream_bd/axi_stream_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_bd || ORIG_REF_NAME==axi_stream_bd} -quiet] -quiet

# IP: bd/axi_stream_bd/ip/axi_stream_bd_processing_system7_0_0/axi_stream_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_bd_processing_system7_0_0 || ORIG_REF_NAME==axi_stream_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/axi_stream_bd/ip/axi_stream_bd_axi_iic_0_0/axi_stream_bd_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_bd_axi_iic_0_0 || ORIG_REF_NAME==axi_stream_bd_axi_iic_0_0} -quiet] -quiet

# IP: bd/axi_stream_bd/ip/axi_stream_bd_axis_fifo_0_0/axi_stream_bd_axis_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_bd_axis_fifo_0_0 || ORIG_REF_NAME==axi_stream_bd_axis_fifo_0_0} -quiet] -quiet

# IP: bd/axi_stream_bd/ip/axi_stream_bd_axis_fifo_1_0/axi_stream_bd_axis_fifo_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_bd_axis_fifo_1_0 || ORIG_REF_NAME==axi_stream_bd_axis_fifo_1_0} -quiet] -quiet

# IP: bd/axi_stream_bd/ip/axi_stream_bd_xbar_1/axi_stream_bd_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_bd_xbar_1 || ORIG_REF_NAME==axi_stream_bd_xbar_1} -quiet] -quiet

# IP: bd/axi_stream_bd/ip/axi_stream_bd_auto_pc_0_1/axi_stream_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_bd_auto_pc_0 || ORIG_REF_NAME==axi_stream_bd_auto_pc_0} -quiet] -quiet

# IP: bd/axi_stream_bd/ip/axi_stream_bd_axi_interconnect_0_1/axi_stream_bd_axi_interconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_bd_axi_interconnect_0_1 || ORIG_REF_NAME==axi_stream_bd_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/axi_stream_bd/ip/axi_stream_bd_rst_ps7_0_125M_0/axi_stream_bd_rst_ps7_0_125M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_bd_rst_ps7_0_125M_0 || ORIG_REF_NAME==axi_stream_bd_rst_ps7_0_125M_0} -quiet] -quiet

# IP: bd/axi_stream_bd/ip/axi_stream_bd_system_ila_0_0/axi_stream_bd_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_bd_system_ila_0_0 || ORIG_REF_NAME==axi_stream_bd_system_ila_0_0} -quiet] -quiet

# IP: bd/axi_stream_bd/ip/axi_stream_bd_axis_i2s_wrapper_0_0/axi_stream_bd_axis_i2s_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_bd_axis_i2s_wrapper_0_0 || ORIG_REF_NAME==axi_stream_bd_axis_i2s_wrapper_0_0} -quiet] -quiet

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: bd/axi_stream_bd/ip/axi_stream_bd_axis_fir_0_0/axi_stream_bd_axis_fir_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_stream_bd_axis_fir_0_0 || ORIG_REF_NAME==axi_stream_bd_axis_fir_0_0} -quiet] -quiet

# IP: ip/fir_bsf_0/fir_bsf_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_bsf_0 || ORIG_REF_NAME==fir_bsf_0} -quiet] -quiet

# IP: ip/fir_bpf_0/fir_bpf_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_bpf_0 || ORIG_REF_NAME==fir_bpf_0} -quiet] -quiet

# IP: ip/fir_hpf_0/fir_hpf_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_hpf_0 || ORIG_REF_NAME==fir_hpf_0} -quiet] -quiet

# IP: ip/fir_lpf_0_1/fir_lpf_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_lpf_0 || ORIG_REF_NAME==fir_lpf_0} -quiet] -quiet

# XDC: o:/ENGS128/lab3/lab3.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: o:/ENGS128/lab3/lab3.gen/sources_1/ip/fir_bsf_0/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_bsf_0 || ORIG_REF_NAME==fir_bsf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: o:/ENGS128/lab3/lab3.gen/sources_1/ip/fir_bpf_0/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_bpf_0 || ORIG_REF_NAME==fir_bpf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: o:/ENGS128/lab3/lab3.gen/sources_1/ip/fir_hpf_0/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_hpf_0 || ORIG_REF_NAME==fir_hpf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: o:/ENGS128/lab3/lab3.gen/sources_1/ip/fir_lpf_0_1/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_lpf_0 || ORIG_REF_NAME==fir_lpf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: o:/ENGS128/lab3/lab3.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: o:/ENGS128/lab3/lab3.gen/sources_1/ip/fir_bsf_0/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_bsf_0 || ORIG_REF_NAME==fir_bsf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: o:/ENGS128/lab3/lab3.gen/sources_1/ip/fir_bpf_0/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_bpf_0 || ORIG_REF_NAME==fir_bpf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: o:/ENGS128/lab3/lab3.gen/sources_1/ip/fir_hpf_0/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_hpf_0 || ORIG_REF_NAME==fir_hpf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: o:/ENGS128/lab3/lab3.gen/sources_1/ip/fir_lpf_0_1/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_lpf_0 || ORIG_REF_NAME==fir_lpf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: o:/ENGS128/lab3/lab3.gen/sources_1/bd/axi_stream_bd/axi_stream_bd_ooc.xdc
